const GATSBY_API_URL: string = process.env.GATSBY_API_URL;
const BASE_URL: string = process.env.GATSBY_APP_BASE_URL || '/';
const GATSBY_APP_AUTH0_DOMAIN: string = process.env.GATSBY_APP_AUTH0_DOMAIN;
const GATSBY_APP_AUTH0_CLIENT_ID: string = process.env.GATSBY_APP_AUTH0_CLIENT_ID;
const GATSBY_APP_BASE_URL: string = process.env.GATSBY_APP_BASE_URL;
const GATSBY_APP_AUTH0_AUDIENCE: string = process.env.GATSBY_APP_AUTH0_AUDIENCE;
const GATSBY_APP_MAPBOX_TOKEN: string = process.env.GATSBY_APP_MAPBOX_TOKEN;
const GATSBY_APP_AUTH0_NAMESPACE: string = process.env.GATSBY_APP_AUTH0_NAMESPACE;
const MAP_PATH: string = process.env.GATSBY_APP_MAP_URL;

export {
  GATSBY_API_URL,
  BASE_URL,
  GATSBY_APP_AUTH0_AUDIENCE,
  GATSBY_APP_AUTH0_CLIENT_ID,
  GATSBY_APP_AUTH0_DOMAIN,
  GATSBY_APP_BASE_URL,
  GATSBY_APP_MAPBOX_TOKEN,
  GATSBY_APP_AUTH0_NAMESPACE,
  MAP_PATH,
};
